name: frontend
description: "Android app for labs management"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.4
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  # HTTP and networking
  http: ^1.2.2

  # State management
  provider: ^6.1.5

  # Storage
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.5.3

  # Authentication
  jwt_decoder: ^2.0.1

  # QR and camera
  qr_flutter: ^4.1.0
  qr_code_scanner_plus: ^2.0.10+1
  image_picker: ^1.0.4

  # Permissions
  permission_handler: ^12.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

flutter_icons:
  android: true
  image_path: "assets/icon/LabsQr_icon.png"

